window.BOGS_DEFAULTS={
 fb:{apiKey:"AIzaSyDg-q3kUE1hb_tRDp1JNff5njBo5Rual5s",authDomain:"bogs-pedidos.firebaseapp.com",projectId:"bogs-pedidos",storageBucket:"bogs-pedidos.firebasestorage.app",messagingSenderId:"915900545559",appId:"1:915900545559:web:679f4779af25b315517a52"},
 settings:{open:true,eta:"35–50 min",closedMsg:"Cocina cerrada · Abrimos Mar a Dom 19:00",ship:1800,freeFrom:25000,transferOff:10,alias:"BOGS.BURZACO",pickup:"Alsina 842, Burzaco",pickupEta:"20–30 min",city:"Burzaco",phone:"5491149948134",phoneShow:"11 4994 8134",features:{freeShipAll:false,coupons:false,club:false},club:{every:5,rewardPct:15},zones:[{name:"Burzaco",cost:1800},{name:"Adrogué",cost:2200},{name:"José Mármol",cost:2200},{name:"Longchamps",cost:2200},{name:"Rafael Calzada",cost:2500},{name:"Glew",cost:2800},{name:"Claypole",cost:2800}],hours:{auto:false,days:[0,2,3,4,5,6],from:"19:00",to:"00:30"},preorder:{enabled:true,lead:45,maxDays:2}},
 cats:["Todos","Hamburguesas","Pizzas NY","Combos","Papas","Bebidas"],
 opts:{b:[["Extra cheddar","Queso fundido extra líquido",1200,"layers"],["Extra medallón","Smash 120 g con costra de fuego",3000,"lunch_dining"],["Agregar papas rústicas","Papas triples fritas con sal marina",2500,"fastfood"],["Sin cebolla","Preferencias de cocción",0,"do_not_disturb_on"]],
  p:[["Doble muzza","Más queso, más estiramiento",2000,"layers"],["Borde relleno","Relleno de cheddar",2500,"donut_large"],["Aceitunas","Verdes descarozadas",800,"circle"],["Sin orégano","Preferencias",0,"do_not_disturb_on"]]},
 menu:[
 {id:"cheese",order:1,cat:1,n:"Cheese Bog's",d:"Pan de papa artesanal, medallón de 120 gs y cheddar fundido al fuego vivo.",p:11000,img:"cheese-bogs.jpg",tag:"120G",o:"b",specs:[["lunch_dining","120g Carne","Smash"],["bakery_dining","Pan de Papa","Esponjoso"],["timer","12 - 15 min","Punto justo"]]},
 {id:"doble",order:2,cat:1,n:"Doble Cheese Bog's",d:"Pan de papa, doble medallón de 120 gs y triple ración de cheddar cremoso.",long:"Pan de papa artesanal dorado a la manteca, doble medallón smash de 120 g con costra crocante y triple feta fundida de queso cheddar puro. Sabor monumental.",p:13000,img:"doble-cheese.jpg",hero:"doble-cheese-hero.jpg",home:"doble-cheese-home.jpg",tag:"TOP",fav:true,featured:true,o:"b",specs:[["lunch_dining","240g Carne","Doble smash"],["bakery_dining","Pan de Papa","Esponjoso"],["timer","15 - 20 min","Punto justo"]]},
 {id:"bacon",order:3,cat:1,n:"Bacon Bog's",d:"Doble medallón, cheddar, panceta crocante y salsa Zeus ahumada.",p:14500,img:"bacon-bogs.jpg",o:"b",specs:[["lunch_dining","240g Carne","Doble smash"],["outdoor_grill","Panceta","Crocante"],["timer","15 - 20 min","Punto justo"]]},
 {id:"olympus",order:4,cat:1,n:"Olympus Triple",d:"Triple medallón, cheddar x4, cebolla crispy y pepinos. Para titanes.",p:17000,img:"olympus-triple.jpg",tag:"XL",o:"b",specs:[["lunch_dining","360g Carne","Triple smash"],["bakery_dining","Pan de Papa","Doble tostado"],["timer","18 - 22 min","Punto justo"]]},
 {id:"muzza",order:5,cat:2,n:"Muzza Gigante",d:"Masa fina y crocante, salsa de tomates italianos cocida lento y abundante muzzarella.",p:7000,img:"muzza-gigante.jpg",tag:"CRUJIENTE",pz:true,o:"p",specs:[["local_pizza","Porción XL","Plegable"],["grain","Masa madre","Fina y crujiente"],["timer","10 - 12 min","Horno de piedra"]]},
 {id:"pepp",order:6,cat:2,n:"Pepperoni Gigante",d:"Masa fina, abundante muzzarella dorada y pepperoni crocante importado estilo NYC.",p:8000,img:"pepperoni-gigante.jpg",tag:"NYC ICON",red:true,pz:true,o:"p",specs:[["local_pizza","Porción XL","Plegable"],["local_fire_department","Pepperoni","Picante suave"],["timer","10 - 12 min","Horno de piedra"]]},
 {id:"duo",order:7,cat:2,n:"Dúo NY",d:"Una muzza + una pepperoni. Dos porciones gigantes para dos dioses.",p:14000,img:"duo-ny.jpg",pz:true,o:"p",specs:[["local_pizza","2 porciones","XL"],["group","Para 2","Compartir"],["timer","12 - 15 min","Horno de piedra"]]},
 {id:"combo1",order:8,cat:3,n:"Combo Cheese",d:"Cheese Bog's + papas Bog's + gaseosa 500 ml.",p:16000,img:"cheese-bogs.jpg",o:"b",specs:[["lunch_dining","Cheese Bog's","120g"],["fastfood","Papas","Porción"],["local_drink","Gaseosa","500 ml"]]},
 {id:"combo2",order:9,cat:3,n:"Combo Doble",d:"Doble Cheese Bog's + papas Bog's + gaseosa 500 ml.",p:18000,img:"doble-cheese-home.jpg",tag:"MÁS PEDIDO",o:"b",specs:[["lunch_dining","Doble Cheese","240g"],["fastfood","Papas","Porción"],["local_drink","Gaseosa","500 ml"]]},
 {id:"papas",order:10,cat:4,n:"Papas Bog's",d:"Siempre frescas, corte bastón, sal marina.",p:5000,ic:"fastfood",specs:[["fastfood","Porción","Para 1-2"],["water_drop","Sal marina","Gruesa"],["timer","8 min","Doble fritura"]]},
 {id:"papasch",order:11,cat:4,n:"Papas Cheddar & Bacon",d:"Cheddar fundido, panceta crocante y verdeo.",p:7500,ic:"fastfood",tag:"TOP",specs:[["fastfood","Porción","Para 2"],["layers","Cheddar","Fundido"],["timer","10 min","Doble fritura"]]},
 {id:"coca",order:12,cat:5,n:"Coca-Cola 500 ml",d:"Bien fría, de la heladera de los dioses.",p:2200,ic:"local_drink",specs:[["ac_unit","Fría","-2°"],["local_drink","500 ml","Botella"],["timer","0 min","Lista"]]},
 {id:"agua",order:13,cat:5,n:"Agua sin gas 500 ml",d:"Mineral, bien fría.",p:1800,ic:"water_drop",specs:[["ac_unit","Fría","-2°"],["water_drop","500 ml","Botella"],["timer","0 min","Lista"]]},
 {id:"birra",order:14,cat:5,n:"Birra IPA 473 ml",d:"Lata artesanal, lúpulo cítrico.",p:4500,ic:"sports_bar",specs:[["ac_unit","Fría","-2°"],["sports_bar","473 ml","Lata"],["timer","0 min","Lista"]]}],
 statuses:[["nuevo","Recibido","Te confirmamos en menos de 5 min","check"],["cocina","En la plancha","Fuego sagrado, medallones frescos","skillet"],["camino","En camino","Aprox. 35–50 min","moped"],["listo","Listo para retirar","Pasá por Alsina 842","storefront"],["entregado","¡Entregado!","Hecha con pasión, servida para vos","celebration"],["cancelado","Cancelado","Escribinos por WhatsApp si fue un error","cancel"]]};
(function(){
 const nowBA=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/Argentina/Buenos_Aires",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date()).map(x=>[x.type,x.value]));return {day:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(p.weekday),min:(+p.hour%24)*60+ +p.minute}};
 const toMin=s=>{const [h,m]=String(s||"0:0").split(":").map(Number);return (h||0)*60+(m||0)};
 window.BOGS_inHours=function(h){if(!h||!h.auto)return true;const {day,min}=nowBA(),f=toMin(h.from),t=toMin(h.to),days=h.days||[];
  if(f<t)return days.includes(day)&&min>=f&&min<t;
  return (days.includes(day)&&min>=f)||(days.includes((day+6)%7)&&min<t)};
 window.BOGS_isOpen=cfg=>!!cfg.open&&window.BOGS_inHours(cfg.hours);
 window.BOGS_hoursText=function(h){if(!h||!h.auto)return "";const n=["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"],d=(h.days||[]).slice().sort();return (d.length===7?"Todos los días":d.map(i=>n[i]).join(", "))+" de "+h.from+" a "+h.to};
})();
// Firestore no permite listas anidadas: specs/extras viajan como objetos y en memoria se usan como tuplas.
window.BOGS_norm=function(p){const o={...p};if(Array.isArray(o.specs))o.specs=o.specs.map(s=>Array.isArray(s)?s:[s.ic||"",s.t||"",s.s||""]);if(Array.isArray(o.extras))o.extras=o.extras.map(x=>Array.isArray(x)?x:[x.n||"",x.d||"",+x.p||0,x.ic||"layers"]);return o};
window.BOGS_toDoc=function(p){const o={...p};if(Array.isArray(o.specs))o.specs=o.specs.map(s=>Array.isArray(s)?{ic:s[0],t:s[1],s:s[2]}:s);if(Array.isArray(o.extras))o.extras=o.extras.map(x=>Array.isArray(x)?{n:x[0],d:x[1]||"",p:+x[2]||0,ic:x[3]||"layers"}:x);return o};

// Pedidos programados: turnos disponibles según la franja de atención, anticipación mínima y días hacia adelante.
window.BOGS_slots=function(cfg,now){now=now||new Date();const h=cfg.hours||{},pre=cfg.preorder||{},days=(h.days&&h.days.length)?h.days:[0,1,2,3,4,5,6];const tm=s=>{const [a,b]=String(s||"0:0").split(":").map(Number);return (a||0)*60+(b||0)};
 const from=tm(h.from||"19:00"),to0=tm(h.to||"00:30"),to=to0>from?to0:to0+1440,lead=+pre.lead||45,maxD=+pre.maxDays||2,step=15,out=[];
 for(let d=0;d<=maxD;d++){const day=new Date(now.getFullYear(),now.getMonth(),now.getDate()+d);if(!days.includes(day.getDay()))continue;for(let m=from;m<=to-15;m+=step){const t=new Date(day.getTime()+m*60000);if(t.getTime()>=now.getTime()+lead*60000)out.push(t)}}return out};
window.BOGS_fmtWhen=function(d,now){now=now||new Date();const sameDay=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();const mañana=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);const hm=d.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit",hour12:false});return (sameDay(d,now)?"hoy":sameDay(d,mañana)?"mañana":d.toLocaleDateString("es-AR",{weekday:"short",day:"2-digit",month:"2-digit"}))+" "+hm};
